//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOSOverlay.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOSOverlay.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AssignmentModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;d51f9f75-2ccd-40e2-bcc9-0d8163beea84&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;1&lt;/CollectionUpdateVersion&gt;
        ///	&lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///	&lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot; /&gt;
        ///&lt;/AssignmentModelCollection&gt;.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CraneConfigModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;9f068291-3364-4f83-98d6-79fd4a4021a5&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;10&lt;/CollectionUpdateVersion&gt;
        ///  &lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///  &lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot;&gt;
        ///    
        ///  &lt;/_Collection&gt;
        ///&lt;/CraneConfigModelCollection&gt;.
        /// </summary>
        internal static string CraneConfigurations {
            get {
                return ResourceManager.GetString("CraneConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DefaultData {
            get {
                object obj = ResourceManager.GetObject("DefaultData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;EnvironmentModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;8eba6c14-0863-4d76-bba7-c814c82f1a7a&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;10&lt;/CollectionUpdateVersion&gt;
        ///  &lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///  &lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot; &gt;
        ///    
        ///    
        ///    
        ///  &lt;/_Collection&gt;
        ///&lt;/EnvironmentModelCol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Environments {
            get {
                return ResourceManager.GetString("Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ExerciseModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;2d9c7c5f-0756-46ca-bce1-9fc2cba36ec5&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;0&lt;/CollectionUpdateVersion&gt;
        ///	&lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///	&lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot; /&gt;
        ///&lt;/ExerciseModelCollection&gt;.
        /// </summary>
        internal static string Exercises {
            get {
                return ResourceManager.GetString("Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;GroupAssignmentModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;3460f5d9-5842-4cba-8d52-07cbf36985c9&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;0&lt;/CollectionUpdateVersion&gt;
        ///	&lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///	&lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot; /&gt;
        ///&lt;/GroupAssignmentModelCollection&gt;.
        /// </summary>
        internal static string GroupAssignments {
            get {
                return ResourceManager.GetString("GroupAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;GroupModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;30960cf2-5757-40ff-ac92-b73f41d59327&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;0&lt;/CollectionUpdateVersion&gt;
        ///  &lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///  &lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot; /&gt;
        ///&lt;/GroupModelCollection&gt;.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ReportModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;22ddaf24-dfa4-4b41-be31-0fa0c319e93b&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;1&lt;/CollectionUpdateVersion&gt;
        ///	&lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///	&lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot; /&gt;
        ///&lt;/ReportModelCollection&gt;.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ScoringDeductionsModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;f3003259-9852-49e5-a4c1-a72c41b808fb&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;1&lt;/CollectionUpdateVersion&gt;
        ///  &lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///  &lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot;&gt;
        ///    
        ///    
        ///    
        ///  &lt;/_Collection&gt;
        ///&lt;/ScoringDeductio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScoringSets {
            get {
                return ResourceManager.GetString("ScoringSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SimulatorSettingsModel xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionMember&gt;false&lt;/CollectionMember&gt;
        ///  &lt;CreatorID&gt;-1&lt;/CreatorID&gt;
        ///  &lt;CreatorUID&gt;00000000-0000-0000-0000-000000000000&lt;/CreatorUID&gt;
        ///  &lt;ID&gt;-1&lt;/ID&gt;
        ///  &lt;IsSubModel&gt;false&lt;/IsSubModel&gt;
        ///  &lt;State&gt;Immutable&lt;/State&gt;
        ///  &lt;UID&gt;08247f94-319c-4e9d-9be2-07484c1b3671&lt;/UID&gt;
        ///  &lt;Master&gt;
        ///    &lt;AdminEnabled&gt;false&lt;/AdminEnabled&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;UserModelCollection xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/IOSOverlay.Data.Models&quot;&gt;
        ///  &lt;CollectionUID&gt;4e873bb4-f312-41a6-8bff-9cd41d97bc20&lt;/CollectionUID&gt;
        ///  &lt;CollectionUpdateVersion&gt;0&lt;/CollectionUpdateVersion&gt;
        ///  &lt;_NextIndex&gt;100&lt;/_NextIndex&gt;
        ///  &lt;_Collection xmlns:d2p1=&quot;http://schemas.datacontract.org/2004/07/System.Collections.ObjectModel&quot;&gt;
        ///    
        ///  &lt;/_Collection&gt;
        ///&lt;/UserModelCollection&gt;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
